pc2_to_grid:
  ros__parameters:
    position_x: -5.0
    position_y: 0.0
    cell_size: 0.1
    length_x: 80.0
    length_y: 80.0
    intensity_factor: 0.2
    height_factor: 1.0
    cloud_in_topic: "/map"
    mapi_topic_name: "/intensity_map"
    maph_topic_name: "/height_map"
    debug: true